name: Terraform Deployment

on:
  push:
    paths:
      - 'infrastructure/terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: infrastructure/terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: infrastructure/terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infrastructure/terraform
