name: Terraform

on:
  pull_request:
    paths:
      - "infrastructure/terraform/**"
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: infrastructure/terraform

      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: infrastructure/terraform
